version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_rds
    environment:
      POSTGRES_USER: sourav
      POSTGRES_PASSWORD: pwd123
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4567:4567"
    volumes:
      - .:/webapp/
      - /webapp/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - db

volumes:
  db_data:
    driver: local